// examples/vue/src/App.vue
<script setup lang="ts">
import ContainerSizeChange from "./ContainerSizeChange.vue";
import NestedScrollBar from "./NestedScrollBar.vue";
import VirtualList from "./VirtualList.vue";
</script>

<template>
	<div>
		<h2>Nested ScrollBar</h2>
		<NestedScrollBar />
		<h2>Virtual List</h2>
		<VirtualList />
		<h2>h2Container Size Change</h2>
		<ContainerSizeChange />
	</div>
</template>

// examples/react/src/App.tsx
import { ContainerSizeChange } from "./ContainerSizeChange";
import { NestedScrollBar } from "./NestedScrollBar";
import { VirtualList } from "./VirtualList";
const App = () => {
	return (
		<div>
			<h2>Nested ScrollBar</h2>
			<NestedScrollBar />
			<h2>Virtual List</h2>
			<VirtualList />
			<h2>Container Size Change</h2>
			<ContainerSizeChange />
		</div>
	);
};

export default App;
