// packages/solid/src/components/HorizontalScrollBar.tsx
import {
	HorizontalScrollBarInstance,
	type ScrollBarOptions,
} from "@ez-kits/scrollbar-core";
import { createEffect, onCleanup } from "solid-js";
import type { WithoutTrackProps, WithTrackProps } from "src/types";

export type HorizontalScrollBarProps = Omit<
	Partial<ScrollBarOptions>,
	"thumb" | "track" | "container"
> &
	(WithTrackProps | WithoutTrackProps);

export type HorizontalScrollBarWithContainerProps = HorizontalScrollBarProps & {
	container?: HTMLElement;
};

export const HorizontalScrollBar = (
	props: HorizontalScrollBarWithContainerProps
) => {
	let thumbRef: HTMLDivElement | undefined;
	let trackRef: HTMLDivElement | undefined;

	const scrollBarInstance = new HorizontalScrollBarInstance({
		container: props.container,
		autoHide: props.autoHide,
		thumb: thumbRef,
		track: trackRef,
		startOffset: props.startOffset,
		endOffset: props.endOffset,
	});
	scrollBarInstance.mount();
	onCleanup(() => {
		scrollBarInstance.unmount();
	});

	createEffect(() => {
		scrollBarInstance.updateOptions({
			container: props.container,
			autoHide: props.autoHide,
			thumb: thumbRef,
			track: trackRef,
			startOffset: props.startOffset,
			endOffset: props.endOffset,
		});
	});

	if (props.withTrack) {
		return (
			<div {...props.trackProps} ref={trackRef}>
				<div {...props.thumbProps} ref={thumbRef} />
			</div>
		);
	}

	return <div {...props} ref={thumbRef} />;
};

// packages/react/src/components/HorizontalScrollBar.tsx
import {
	HorizontalScrollBarInstance,
	type ScrollBarOptions,
} from "@ez-kits/scrollbar-core";
import { useEffect, useRef, useState, type RefObject } from "react";
import type { WithoutTrackProps, WithTrackProps } from "src/types";
import { maybeRefToValue } from "src/utilities";

export type HorizontalScrollBarProps = Omit<
	Partial<ScrollBarOptions>,
	"thumb" | "track" | "container"
> &
	(WithTrackProps | WithoutTrackProps);

export type HorizontalScrollBarWithContainerProps = HorizontalScrollBarProps & {
	container?: HTMLElement | RefObject<HTMLElement | null | undefined>;
};

export const HorizontalScrollBar = ({
	container,
	autoHide = true,
	startOffset,
	endOffset,
	withTrack = false,
	thumbProps = {},
	trackProps = {},
	...props
}: HorizontalScrollBarWithContainerProps) => {
	const trackRef = useRef<HTMLDivElement>(null);
	const thumbRef = useRef<HTMLDivElement>(null);

	const [scrollBarInstance] = useState(
		() =>
			new HorizontalScrollBarInstance({
				container: maybeRefToValue(container) || undefined,
				thumb: thumbRef.current || undefined,
				track: trackRef.current || undefined,
				startOffset,
				endOffset,
				autoHide,
			})
	);

	scrollBarInstance.updateOptions({
		container: maybeRefToValue(container) || undefined,
		thumb: thumbRef.current || undefined,
		track: trackRef.current || undefined,
		startOffset,
		endOffset,
		autoHide,
	});

	useEffect(() => {
		return scrollBarInstance.mount();
	}, [scrollBarInstance]);

	if (withTrack) {
		return (
			<div {...props} ref={trackRef} {...trackProps}>
				<div ref={thumbRef} {...thumbProps} />
			</div>
		);
	}

	return <div {...props} ref={thumbRef} />;
};
