// packages/react/src/types.ts
import type { HTMLAttributes } from "react";

export type WithTrackProps = {
	withTrack: true;
	thumbProps?: HTMLAttributes<HTMLDivElement>;
	trackProps?: HTMLAttributes<HTMLDivElement>;
};

export type WithoutTrackProps = {
	withTrack?: false;
	thumbProps?: undefined;
	trackProps?: undefined;
} & HTMLAttributes<HTMLDivElement>;

// packages/solid/src/types.ts
import type { JSX } from "solid-js";

export type WithTrackProps = {
	withTrack: true;
	thumbProps?: JSX.HTMLAttributes<HTMLDivElement>;
	trackProps?: JSX.HTMLAttributes<HTMLDivElement>;
};

export type WithoutTrackProps = {
	withTrack?: false;
	thumbProps?: undefined;
	trackProps?: undefined;
} & JSX.HTMLAttributes<HTMLDivElement>;
